language: ruby

rvm:
  - ruby-head
  - 2.3.1
  - 2.2.5
  - 2.1.10

before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
  - gem cert --add <(curl -Ls http://www.zenspider.com/~ryan/gem-public_cert.pem)
  - gem cert --add certs/tangrufus.pem

bundler_args: --without tools --trust-policy=MediumSecurity --jobs=3 --retry=3

branches:
  only:
    - master

sudo: false

cache: bundler

notifications:
  email: false
