language: ruby

rvm:
  - ruby-head
  - 2.3.0
  - 2.2.4
  - 2.1.10

before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler

branches:
  only:
    - master

sudo: false

cache: bundler

notifications:
  email: false
